=== pritibiyani/JsonSchemaDemo/schema/book_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "author": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "price": {
      "type": "number",
      "minimum": 0,
      "exclusiveMinimum": true
    },
    "characters": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "adultBook": {
      "type": "boolean"
    },
    "publishedOn": {
      "type": "string",
      "format": "date-time"
    },
    "category": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "author",
    "title",
    "price"
  ]
}

=== pritibiyani/JsonSchemaDemo/resources/book.json
{
  "author": "J. K. Rolling",
  "title": "Harry Potter and the Philosopher's Stone (",
  "price": 200.12,
  "characters": ["Harry",
    "Ron",
    "Hermione"
  ],
  "adultBook": false,
  "publishedOn": "2016-06-26T00:00:00-04:00",
  "category": ["Fantasy",
    "drama",
    "fiction",
    "mystery"
  ]
}
